name: profile_card_app
description: Flutter UI Assignment - Profile Card

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  # Register the resource image as an asset.
  # Place resource.jpeg inside an 'assets/' folder at the project root.
  assets:
    - assets/icon.jpg